const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  darkMode: state => state.app.darkMode,
  clientHeight: state => state.app.clientHeight,
  clientWidth: state => state.app.clientWidth,
  showSearch: state => state.app.showSearch,
  signalRTableData: state => state.app.signalRTableData,
  paySuccessData: state => state.app.paySuccessData,
  uploaderVisible: state => state.app.uploaderVisible,
  uploaderTab_Index: state => state.app.uploaderTab_Index,
  fileDataClone: state => state.app.fileDataClone,
  fileDataClone_DataNumber: state => state.app.fileDataClone_DataNumber,
  downLoadFileDataClone: state => state.app.downLoadFileDataClone,
  preViewContainerVisible: state => state.app.preViewContainerVisible,
  preViewContainerData: state => state.app.preViewContainerData,
  corpSpaceContainerVisible: state => state.app.corpSpaceContainerVisible,
  registedPersonContainerVisible: state => state.app.registedPersonContainerVisible,
  corpIdForProjectSpace: state => state.app.corpIdForProjectSpace,
  projectSpaceDialogVisible: state => state.app.projectSpaceDialogVisible,
  preViewDownloadBtnVisible: state => state.app.preViewDownloadBtnVisible,
  activeTab: state => state.app.activeTab,
  shareMode: state => state.app.shareMode,
  modelPreViewContainerVisible: state => state.app.modelPreViewContainerVisible,
  modelPreViewContainerDisplayVisible: state => state.app.modelPreViewContainerDisplayVisible,
  shareCountItemContainerVisible: state => state.app.shareCountItemContainerVisible,
  partOfDeleteSuccessContainerVisible: state => state.app.partOfDeleteSuccessContainerVisible,
  modelPreViewInitUrl: state => state.app.modelPreViewInitUrl,
  projectList: state => state.app.projectList,
  projectCode: state => state.app.projectCode,
  projectLeftMenuActive: state => state.app.projectLeftMenuActive,
  projectPageScrollTop: state => state.app.projectPageScrollTop,
  projectPageIndex: state => state.app.projectPageIndex,
  projectPageNumber: state => state.app.projectPageNumber,
  queryResourceTree: state => state.app.queryResourceTree,
  queryPrivateResourceTree: state => state.app.queryPrivateResourceTree,
  
  currApp: state => state.app.currApp,

  token: state => state.user.token,
  avatar: state => state.user.avatar,
  bitpop: state => state.user.bitpop,
  hasNotDealApply: state => state.user.hasNotDealApply,
  name: state => state.user.name,
  roles: state => state.user.roles,
  user: state => state.user.user,
  pwdDialogVisible: state => state.user.pwdDialogVisible,
  messageList: state => state.user.messageList,
  messageListCount: state => state.user.messageListCount,
  inDingTalk: state => state.user.inDingTalk,

  currentRoute: state => state.route.currentRouteName,

  menus: state => state.permissions.menus,
  permi: state => state.permissions.permi,
  components: state => state.permissions.components,
  routerMap: state => state.permissions.routerMap,
  isAdminLogon: state => state.permissions.isAdminLogon,
  permissionsLoaded: state => state.permissions.loaded
}
export default getters
